apiVersion: v1
kind: Service
metadata:
  name: whatsit-api
  namespace: whatsit
  labels:
    name: whatsit-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: whatsit-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatsit-api
  namespace: whatsit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: api
        name: whatsit-api
    spec:
      containers:
      - image: gcr.io/whatsit-174908/whatsit-api:latest
        name: whatsit-api
        ports:
        - containerPort: 8080
